# Header
menu:
  归档: /archives
  微博: http://weibo.com
#  贴吧: http://tieba.baidu.com
  推特: http://twitter.com
  github: http://github.com
# rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: true
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: ture

# display index within the page 显示页内索引
post_index: true

# disqus shortname
disqus: h2x

# Miscellaneous
google_analytics: 
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
